// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  spaces = 16,
  newline = 17,
  LineComment = 1,
  BlockComment = 2,
  File = 3,
  Instruction = 4,
  Label = 5,
  Identifier = 6,
  Number = 7,
  RegisterExpression = 8,
  Register = 9,
  Directive = 10,
  String = 11
